package com.cg.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/*
 * This is the basic controller for establishing the inbuilt security provided by Spring
 * In this password is generated by System and Each time you run the application,
 *  spring boot will generate a different password for you. 
 */

@RestController
public class HomeController {
	
	@GetMapping("/")
	public String text() {
		return "Hello Developer your API is working fine";
	}

	
	@GetMapping("/about")
	public String about() {
		return "This is the basic implementation of Spring Security";
	}
}
